### ISSUE TITLE
[Bug] Broken `bf.Collider.new` function

### ISSUE THREAD

**Issue by alexmozaidze** [HDictus/breezefield#14]
I tried using `bf.Collider.new(world, "Circle", {0, 0, 20})` like in the basic example in README, but it didn't work.

The reason this occurs is because the `...` argument table gets wrapped in another table:
```lua
function Collider.new(world, collider_type, ...)
   -- deprecated
   return world:newCollider(collider_type, {...})
end
```
Removing the brackets fixes the issue:
```lua
function Collider.new(world, collider_type, ...)
   -- deprecated
   return world:newCollider(collider_type, ...)
end
```

**Comment by HDictus** [comment]
Hey Alexmozaidze, thanks for your feedback.

Ah, that isn't actually intended usage but I can absolutely see why you go that from the README.  The ... should contain whatever args should be passed love.physics.newBody, which for e.g. polygon can accept either  vertex positions `x1, y1, x2, y2...` or vertices as a table `{x1, y1, x2, y2, ...}`.  The implementation you propose would break that, and also break the intended usage `world, "Circle", 0, 0, 20` . We could come up with something more complex to fit all usecases, but since this function is deprecated I would prefer to just remove it soon.

to avoid confusion caused by this function and allow passing subsequent args (e.g. `table_to_use`), `world:newCollider()` takes the newBody args as a table only (so `{x1, y1, x2, y2, ...}` or `{{x1, y1, x2, y2, ...}}`, and bf.Collider.new is deprecated, and may be removed in a later version. I'll add a proper statement of warning to it and remove it from the README.

**Comment by HDictus** [comment]
see #19
